#!/bin/sh

# start up script for local running copy of mysql (client)
# essentially just an alias
pushd $(dirname $0) >/dev/null; HERE=`pwd`; popd >/dev/null;

mysql --defaults-file=$HERE/mysql.conf $@