#!/bin/sh

# start up script for local running copy of mysql (server)
# this script runs mysqld as your current user with data stored in the same directory this script resides in.
# And it leaves the db-root account password blank.

pushd $(dirname $0) >/dev/null ; HERE=`pwd`; popd  >/dev/null #this tricky from lighty.sh; I'm not going to doc it here again

# HERE is (absolute and direct) the location of this script, *not* the current working directory


# TODO: erase if exists??
rm -r $HERE/{tmp,data}
mkdir $HERE/{tmp,data}

# Of course, MySQL is picky about having absolute paths as well. Why wouldn't it be? Everything else is.
# Fastest fix: import the entire cnf file in a giant heredoc

# MySQL, of course, uses itself to hold metadata about itself
# So it cannot run on its own and must be bootstrapped by this other script
mysql_install_db --basedir=/usr --ldata=$HERE/data

# Actually start the server
mysqld --defaults-file=$HERE/mysql.conf